library(igraph)
library(visNetwork)
library(readr)
#library(graphTweets)

### define functions
coord_nx_nodes <- function(filename){
  g <- read_graph(filename, format="graphml") #use the graphml file generated by coordination_network_toolkit in Py
  V(g)$bt <- betweenness(g, directed=F, weights=E(g)$weight) #calculate betweenness centrality
  V(g)$degree <- degree(g,mode = "all") #get degree centrality
  V(g)$authority<- authority.score(g)$vector #get authority scores but its use is limited due to undirected graph
  
  ceb <- igraph::cluster_louvain(g,weights = E(g)$weight) #use louvain algorithm to cluster the graph
  V(g)$louvain <- ceb$membership
  walktrap <- cluster_walktrap(g,weights = E(g)$weight) #use walktrap method to cluster
  V(g)$walktrap <- walktrap$membership
  
  g_nodes <-  as.data.frame(get.vertex.attribute(g)) # create a dataframe for node-level metrics
  write.csv(g_nodes,paste0(filename,"_nodes.csv")) #save the dataframe as csv
  return(g_nodes)
}

coord_nx_edges <- function(filename){
  g <- read_graph(filename, format="graphml")
  g_edge <-  as.data.frame(get.edgelist(g)) #get raw edgelist
  g_edge_attribute <-  as.data.frame(get.edge.attribute(g)) #get edge attributes
  g_edgelist <- cbind(g_edge,g_edge_attribute) #merge raw edgelist and edge attributes
  write.csv(g_edgelist,paste0(filename,"_edges.csv")) #save the edge info as csv
  return(g_edgelist)
}

vis_kcore <- function(filename,k){
  g <- read_graph(filename, format="graphml")
  
  V(g)$bt <- betweenness(g, directed=F, weights=E(g)$weight) 
  ceb <- igraph::cluster_louvain(g,weights = E(g)$weight)
  V(g)$louvain <- ceb$membership
  walktrap <- cluster_walktrap(g,weights = E(g)$weight)
  V(g)$walktrap <- walktrap$membership
  
  kcore <- coreness(g, mode="all")
  kc <- induced_subgraph(g, kcore>=k) #get k-core
  V(kc)$group <- V(kc)$louvain #color nodes by cluters identified by the louvain algorithm 
  #V(kc)$group <- V(kc)$walktrap
  V(kc)$size <- V(kc)$bt/300 #size nodes by betweenness centrality
  V(kc)$label <- V(kc)$username #use username as node label
  
  nodes_k <- as.data.frame(get.vertex.attribute(kc)) #create node dataframe
  edge_k <-  as.data.frame(get.edgelist(kc)) #create edge dataframe 
  
  vis <- visNetwork(nodes_k,edge_k, height = "1000px", width = "100%") #create the vis
  visSave(vis, file=paste0(filename,"_vis.html"), selfcontained = TRUE, background = "white") #save the vis as html file
  return(vis)
}

g_nodes <- coord_nx_nodes("covidtweets_aprilw3_cotweet_60s.graphml")
g_edgelist <- coord_nx_edges("covidtweets_aprilw3_cotweet_60s.graphml")
vis_kcore("covidtweets_aprilw3_cotweet_60s.graphml",3)

## inspect identified tweets and profiles
tweets_profile_coordnx <- read_csv("identified_tweets_basedon_coordnx/tweets_coordnx_aprilw3.csv")
g_nodes$username <- tolower(g_nodes$username)
tweets_profile_coordnx_nxmetrics <- merge(tweets_profile_coordnx, g_nodes[,c("username","id","bt","degree","authority","louvain","walktrap")],by = "username", all.x = TRUE)
save(tweets_profile_coordnx,tweets_profile_coordnx_nxmetrics, file="coord_nx_aprilw3.rda")

